package com.better.CommuteMate.domain.schedule.repository;

import com.querydsl.jpa.impl.JPAQueryFactory;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.jdbc.Sql;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = "spring.jpa.hibernate.ddl-auto=none")
@Sql(statements = {
        "DROP TABLE IF EXISTS work_schedule",
        "CREATE TABLE work_schedule (" +
                "schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_id BIGINT NOT NULL, setting_id BIGINT NOT NULL, workplace_id BIGINT NOT NULL," +
                "date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL," +
                "status_code VARCHAR(4) NOT NULL, work_status_code VARCHAR(4)," +
                "attendance_status_code VARCHAR(4), created_request_id VARCHAR(36)," +
                "created_at TIMESTAMP NOT NULL, created_by VARCHAR(36)," +
                "updated_at TIMESTAMP, updated_by VARCHAR(36))",
        // user 1: apply(이른) - MAX 후보 아님
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_request_id, created_at) " +
                "VALUES (1, 1, 1, DATE '2026-08-10', TIME '09:00:00', TIME '09:30:00', 'WS02', NULL, TIMESTAMP '2026-08-10 09:00:00')",
        // user 1: apply(늦은) - 이게 apply 중 MAX여야 함
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_request_id, created_at) " +
                "VALUES (1, 1, 1, DATE '2026-08-15', TIME '09:00:00', TIME '09:30:00', 'WS02', NULL, TIMESTAMP '2026-08-15 09:00:00')",
        // user 1: edit(CR01 승인) - apply보다 더 늦지만 제외되어야 함
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_request_id, created_at) " +
                "VALUES (1, 1, 1, DATE '2026-08-20', TIME '09:00:00', TIME '09:30:00', 'WS02', '555', TIMESTAMP '2026-08-20 09:00:00')",
        // user 2: apply만 존재 - 사용자 필터링(격리) 검증용
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_request_id, created_at) " +
                "VALUES (2, 1, 1, DATE '2026-08-25', TIME '09:00:00', TIME '09:30:00', 'WS02', NULL, TIMESTAMP '2026-08-25 09:00:00')",
        // user 3: edit만 존재, apply 이력 없음 - null 반환 검증용
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_request_id, created_at) " +
                "VALUES (3, 1, 1, DATE '2026-08-05', TIME '09:00:00', TIME '09:30:00', 'WS02', '777', TIMESTAMP '2026-08-05 09:00:00')"
})
class WorkSchedulesRepositoryLastAppliedAtTest {

    @MockBean JPAQueryFactory queryFactory;
    @Autowired WorkSchedulesRepository repository;

    @Test
    @DisplayName("apply row 중 가장 늦은 created_at을 반환하고, 더 늦은 edit row는 제외한다")
    void excludesEditRowEvenWhenItIsLaterThanApplyRows() {
        LocalDateTime result = repository.findLastAppliedCreatedAtByUserId(1L);

        assertThat(result).isEqualTo(LocalDateTime.of(2026, 8, 15, 9, 0, 0));
    }

    @Test
    @DisplayName("apply 이력이 전혀 없고 edit row만 있으면 null을 반환한다")
    void returnsNullWhenOnlyEditRowsExist() {
        LocalDateTime result = repository.findLastAppliedCreatedAtByUserId(3L);

        assertThat(result).isNull();
    }

    @Test
    @DisplayName("다른 사용자의 apply row에 영향을 받지 않고 해당 userId로만 격리된다")
    void isolatesResultByUserId() {
        LocalDateTime result = repository.findLastAppliedCreatedAtByUserId(2L);

        assertThat(result).isEqualTo(LocalDateTime.of(2026, 8, 25, 9, 0, 0));
    }

    @Test
    @DisplayName("존재하지 않는 사용자는 null을 반환한다")
    void returnsNullForUnknownUser() {
        LocalDateTime result = repository.findLastAppliedCreatedAtByUserId(999L);

        assertThat(result).isNull();
    }
}
