package com.better.CommuteMate.domain.schedule.repository;

import com.better.CommuteMate.global.code.CodeType;
import com.querydsl.jpa.impl.JPAQueryFactory;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.jdbc.Sql;

import java.time.LocalDate;
import java.time.LocalTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = "spring.jpa.hibernate.ddl-auto=none")
@Sql(statements = {
        "DROP TABLE IF EXISTS work_schedule",
        "CREATE TABLE work_schedule (" +
                "schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_id BIGINT NOT NULL, setting_id BIGINT NOT NULL, workplace_id BIGINT NOT NULL," +
                "date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL," +
                "status_code VARCHAR(4) NOT NULL, work_status_code VARCHAR(4)," +
                "attendance_status_code VARCHAR(4), created_request_id VARCHAR(36)," +
                "created_at TIMESTAMP NOT NULL, created_by VARCHAR(36)," +
                "updated_at TIMESTAMP, updated_by VARCHAR(36))",
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_at) " +
                "VALUES (1, 1, 1, DATE '2026-08-18', TIME '09:00:00', TIME '09:30:00', 'WS04', CURRENT_TIMESTAMP)",
        "INSERT INTO work_schedule " +
                "(user_id, setting_id, workplace_id, date, start_time, end_time, status_code, created_at) " +
                "VALUES (1, 1, 1, DATE '2026-08-18', TIME '09:00:00', TIME '09:30:00', 'WS02', CURRENT_TIMESTAMP)"
})
class WorkSchedulesRepositorySlotRegressionTest {

    @MockBean JPAQueryFactory queryFactory;
    @Autowired WorkSchedulesRepository repository;

    @Test
    @DisplayName("취소 후 재신청한 동일 슬롯 조회 시 활성 스케줄을 한 건 반환한다")
    void findsActiveScheduleWhenCancelledHistoryExistsForSameSlot() {
        var result = repository
                .findFirstByUser_UserIdAndDateAndStartTimeAndEndTimeAndStatusCodeInOrderByUpdatedAtDesc(
                1L,
                LocalDate.of(2026, 8, 18),
                LocalTime.of(9, 0),
                LocalTime.of(9, 30),
                java.util.List.of(CodeType.WS01, CodeType.WS02)
        );

        assertThat(result).isPresent();
        assertThat(result.orElseThrow().getStatusCode()).isEqualTo(CodeType.WS02);
    }
}
